- block:
  - name: KnownFolders
    include_role:
      name: win_knownFolders
    vars:
      knownFolder: "{{args.knownFolder | mandatory}}"
      path: "{{args.path | mandatory}}"
    # debug:
      # msg: "{{args}}"
    