- block:
  # - name: Set hibernation file size
  #   debug:
  #     msg: "{{args}}"
  - name: Set hibernation file size
    include_role:
      name: win_hibernate
    vars:
      size: "{{args.size}}"
