---
user_home: "%userprofile%" #cmd path
mass_storage_path: "C:\\" #cmd path"
fast_storage_path: "C:\\" #cmd path"
root_dir_structure:
  install: yes
  win_path:
    - elements:
        - "{{user_home}}\\bin"
      scope: user
  win_desktopini:
    - path: "{{user_home}}\\Documents\\source"
      IconResource: C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico,0
    - path: "{{fast_storage_path}}\\VirtualMachines"
      IconResource: 'C:\Windows\System32\setupapi.dll,47'
    - path: "{{user_home}}\\bin"
      IconResource: 'C:\WINDOWS\System32\SHELL32.dll,314'
    - path: "{{mass_storage_path}}\\Games"
      IconResource: 'C:\Windows\system32\setupapi.dll,36'
    - path: "{{mass_storage_path}}\\Entertainment"
      IconResource: 'C:\Windows\system32\wmploc.dll,91'
  win_file:
    - path: "{{user_home}}\\Documents\\source\\thirdparty"
      state: directory
    - path: "{{user_home}}\\Documents\\source\\inDev"
      state: directory
    - path: "{{user_home}}\\Documents\\source\\trashDev"
      state: directory
    - path: "{{fast_storage_path}}\\VirtualMachines\\Virtual Hard Disks"
      state: directory
    # linux dirs
    - path: "{{user_home}}\\etc" #
      state: directory
    - path: "{{user_home}}\\opt" #Aka program files
      state: directory
    - path: "{{user_home}}\\var"
      state: directory
    - path: "{{user_home}}\\var\\log"
      state: directory
wsl_packages:
  install: yes
  choco_packages:
    - name: wsl-ubuntu-2004
    - name: wsl2
    # - lxrunoffline
vagrant_home:
  install: yes
  win_environment:
    - name: VAGRANT_HOME
      value: "{{fast_storage_path}}\\VirtualMachines\\.vagrant.d"
      level: user
vagrant_default_provider:
general_dev_tools:
  install: yes
  choco_packages:
    - name: gsudo
    - name: docker-desktop
    - name: vagrant
    - name: vscode
    - name: git
    - name: poshgit
    - name: powershell-core
  include_task:
    - file: git_config.yml
    - file: wsl2.yml
    - file: consoles_config.yml
misc:
  install: yes
  choco_packages:
    - name: 7zip
    - name: autohotkey
    - name: Everything
    - name: vlc
#     - name: Recuva # issue with checksum 26/07/2022
    - name: mousewithoutborders
    - name: wizTree
    - name: discord
    - name: zoom
#     - name: jdownloader # issue with url 26/07/2022
    - name: qbittorrent
    - name: bitwarden
    - name: googledrive
    - name: office365business
      package_params: '/exclude:"Access Groove Lync OneDrive OneNote Outlook Publisher" /eula:"true"'
misc_misc:
  install: yes
  choco_packages:
    - name: audacity
    - name: audacity-ffmpeg
java:
  - name: jre8
  - name: jdk8
rust:
  install: yes
  choco_packages:
    - name: cmake
    - name: cygwin
    - name: make
    - name: rust
    - name: bazel
go:
  install: yes
  choco_packages:
    - name: golang
python:
  install: yes
  python_packages:
    - name: pip --upgrade
    - name: pipx
    - name: tox
    - name: black
    - name: virtualenv
nodejs:
  install: yes
  node_modules:
    - name: npm
      use: yes
    - name: typescript
    - name: ts-node
    - name: eslint
    - name: prettier
  choco_packages:
    - name: curl
    - name: wget
store:
  install: yes
  windows_store:
    - uri: "https://www.microsoft.com/en-us/p/dynamic-theme/9nblggh1zbkw"
debloat:
# Clear everything from start?
  install: yes
  uninstall_appx:
    - name: "Disney.37853FC22B2CE"
    - name: "Microsoft.BingNews"
    - name: "Microsoft.Getstarted"
    - name: "Microsoft.MicrosoftOfficeHub"
    - name: "Microsoft.MicrosoftOfficeHub"
    - name: "Microsoft.MicrosoftSolitaireCollection"
    - name: "microsoft.windowscommunicationsapps"
    - name: "Microsoft.ZuneMusic"
    - name: "Microsoft.ZuneVideo"
    - name: "EclipseManager"
    - name: "ActiproSoftwareLLC"
    - name: "AdobeSystemsIncorporated.AdobePhotoshopExpress"
    - name: "Duolingo-LearnLanguagesforFree"
    - name: "PandoraMediaInc"
    - name: "CandyCrush"
    - name: "BubbleWitch3Saga"
    - name: "Wunderlist"
    - name: "Flipboard"
    - name: "Twitter"
    - name: "Facebook"
    - name: "Royal Revolt"
    - name: "Sway"
    - name: "Speed Test"
    - name: "Dolby"
    - name: "Viber"
    - name: "ACGMediaPlayer"
    - name: "Netflix"
    - name: "OneCalendar"
    - name: "LinkedInforWindows"
    - name: "HiddenCityMysteryofShadows"
    - name: "Hulu"
    - name: "HiddenCity"
    - name: "AdobePhotoshopExpress"
    - name: "HotspotShieldFreeVPN"
  reg_edits:
    - name: disable_chat_icon_on_taskbar_for_all_users.reg
    - name: remove_widgets_button_on_taskbar_in_windows_11.reg
    - name: disable_onedrive_for_all_users.reg
    - name: turn_off_onedrive_run_at_startup.reg
security:
  install: yes
  reg_edits:
    - name: admin_uac_password.reg
personalize:
  install: yes
  reg_edits:
    - name: turn_on_restart_apps_after_sign_in_for_current_user.reg
    - name: automaticaccentcolor.reg
    - name: use_dark_theme_color_for_default_app_mode_for_current_user.reg
    - name: use_dark_theme_color_for_default_windows_mode_for_current_user.reg
    - name: enable_last_active_click.reg
    - name: enable_clipboard_history_for_all_users.reg
    - name: enable_clipboard_sync_across_devices_for_all_users.reg
    - name: turn_on_clipboard_sync_across_your_devices_and_automatically_sync.reg
    - name: explorer.reg
    - name: restore_the_classic_context_menus_in_windows_11.reg
    - name: show_open_windows_only.reg
    - name: start_layout_show_more_recommendations.reg
    - name: win32_long_paths_enable.reg
set_hibernate:
  install: yes
  win_hibernate:
    - size: 100
start_menu_customization:
  install: yes
  download_file:
    - url: https://raw.githubusercontent.com/YoraiLevi/ansible_playbooks/master/playbooks/files/start.bin
      dest: '%LocalAppData%/Packages/Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy/LocalState/start.bin'
ahk_tts:
  install: yes
  reg_edits:
    - name: eva.reg
  win_file:
    - path: "{{user_home}}/bin/TTS"
      state: directory
  download_file:
    - url: https://github.com/YoraiLevi/autohotkeys/releases/latest/download/main.exe
      dest: "{{user_home}}/bin/TTS/TTS.exe"
  win_scheduled_task:
    - name: TTS
      run_level: highest
      actions:
        - path: "{{user_home}}/bin/TTS/TTS.exe"
      triggers:
        - type: logon
ahk_remapper_url: https://github.com/YoraiLevi/autohotkeys/releases/latest/download/BaseRemap.exe
ahk_remapper:
  install: yes
  win_file:
    - path: "{{user_home}}/bin/KeyboardRemap"
      state: directory
  download_file:
    - url: "{{ahk_remapper_url}}"
      dest: "{{user_home}}/bin/KeyboardRemap/KeyRemap.exe"
  win_scheduled_task:
    - name: Remap Keys
      run_level: highest
      actions:
        - path: "{{user_home}}/bin/KeyboardRemap/KeyRemap.exe"
      triggers:
        - type: logon


#Install Interception driver


# https://windowsloop.com/enable-developer-mode-windows-10/
# Get-Partition -DiskPath "\\?\usbstor#disk&ven__usb&prod__sandisk_3.2gen1&rev_1.00#010159aa95e629484cb55cce6f49dc91600e3979810843cf60342c1ab877b14#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}" | %{ Remove-PartitionAccessPath -DiskNumber $_.DiskNumber -PartitionNumber $_.PartitionNumber -AccessPath "$($_.DriveLetter):"}
# Get-Partition -DiskPath "\\?\usbstor#disk&ven__usb&prod__sandisk_3.2gen1&rev_1.00#010159aa95e629484cb55cce6f49dc91600e3979810843cf60342c1ab877b14#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}" | Add-PartitionAccessPath -AccessPath C:\FileHistory\
# netsh advfirewall firewall set rule group="Network Discovery" new enable=Yes
# https://superuser.com/questions/1044050/configuring-windows-8-8-1-10-file-history-via-command-line
# http://blog.bitcollectors.com/adam/2017/07/file-history-command-line-tool/
#   # set region of windows
#   - script: PowerShell Get-WinHomeLocation; PowerShell Set-WinHomeLocation -GeoID 117
# https://engineering.thetrainline.com/scripting-language-and-region-settings-for-current-user-default-user-and-welcome-screen-859bbd58900d

# set login image
# https://c-nergy.be/blog/?p=15168
# https://www.joseespitia.com/2017/09/15/set-wallpaper-powershell-function/
# https://www.osource.se/index.php/custom-lockscreen-image-in-windows-10-with-powershell/
#https://www.powershellgallery.com/packages/Set-LockScreen/1.0/Content/Set-LockScreen.ps1
#     #Unnecessary Windows 10 AppX Apps

#     #Sponsored Windows 10 AppX Apps
#     #Add sponsored/featured apps to remove in the "*AppName*" format

