- name: update-help powershell
  win_shell: "Update-Help -ErrorAction SilentlyContinue -Force;exit 0"
  register: powershell
  changed_when: false
- name: update-help powershell-core
  win_shell: "Update-Help -ErrorAction SilentlyContinue -Force;exit 0"
  args:
    executable: pwsh
  register: pwsh
  changed_when: false
- name: config git correctly
  ansible.windows.win_powershell:
    script: |
      $Target =  "$({{target}})"
      git config --global core.autocrlf false
      git config --global core.editor "code --wait"
      git config --global user.name "{{_full_name}}"
      git config --global user.email "{{_email}}"
      # https://about.gitlab.com/blog/2020/04/07/15-git-tips-improve-workflow/
      git config --global core.excludesFile $(Join-Path $Target /.gitignore)
      git config --global rebase.autosquash true

      if($changed -eq $true){
        Write-Output "changed"
      }
      else{
          Write-Output "ok"
      }
  # changed_when: '"changed" in git.output'
  # register: git
  vars:
    target: '[System.Environment]::ExpandEnvironmentVariables("{{root}}")'

