---
- hosts: all
  tasks: 
    - block:
      - win_tempfile:
          state: directory
          suffix: build
        register: tmp
      - ansible.windows.win_file:
          path: "{{tmp.path}}/{{item}}"
          state: directory
        loop: 
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
      when: ansible_system == "Win32NT"