---
- hosts: WindowsPersonal
  tasks:
    - name: restart explorer.exe
      win_command: cmd.exe /c "taskkill /im explorer.exe /f && start explorer.exe"
      changed_when: false
  # roles:
    # - role: windows-software
    # - role: windows-folder-structure
- hosts: WSLPersonal
  roles:
    - role: wsl-personal

  # tasks:
  #   - name: Personalize Windows
  #     include: tasks/Personal_Windows.yml
  #     when: ansible_system == "Win32NT"
  #   - name: Personalize WSL
  #     when: ansible_system == "Linux"

